# Login
POST {{host}}/login-register
Content-Type: application/json

{
  "email": "test@me.com",
  "hashedPassword": "test"
}

> {%
  client.assert(
    typeof response.body.token !== "undefined",
    "No token returned"
  );
  client.global.set("auth_token", response.body.token);
%}

###

# Get the number of countdowns a user has
GET {{host}}/numcd
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{

}

###

# Insert a countdown
POST {{host}}/cd
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "124",
  "owner": "test@me.com",
  "name": "testing",
  "gradient": ["purple", "green"],
  "date": "1540871378369"
}

###

# Get a countdown
GET {{host}}/cd?id=124
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# Update a countdown
PATCH {{host}}/cd
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "124",
  "owner": "test@me.com",
  "name": "not testing",
  "gradient": ["purple", "green"],
  "date": "1540871378369"
}

###

# Delete a countdown
DELETE {{host}}/cd
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "124"
}

###
